[package]
name = "c-guest-host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
risc0-zkvm = { version = "=1.0.1" }
serde = "1.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
